import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:pet_adoption/repos/posts_data.dart';

final petData = [
  // 🐶 Dogs
  {
    "id": 1,
    "name": "Max",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/dog1_1.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2RvZzFfMS5qcGVnIiwiaWF0IjoxNzU1MDExODkxLCJleHAiOjE3ODY1NDc4OTF9.ELQ40Bhr-b5ebtq3s3eArRWHwzS_90EihboNJ17RMOc",
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/dog1_2.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2RvZzFfMi5qcGVnIiwiaWF0IjoxNzU1MDExOTA5LCJleHAiOjE3ODY1NDc5MDl9.ntM9b87-SsWWy9DdO9q9jc1sv_-GAO2FnXRAZ2-UV2A",
    ],
    "type": "Dogs",
    "weight": 25.5,
    "age": 3,
    "breed": "Golden Retriever",
    "gender": "male",
    "location": "Cairo, Egypt",
    "description": "Friendly and playful, loves long walks and kids.",
    "characteristics": ["Playful", "Friendly", "Active"],
    "isVaccinated": true,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:15:00Z",
  },
  {
    "id": 2,
    "name": "Bella",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/dog2_1.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2RvZzJfMS5qcGVnIiwiaWF0IjoxNzU1MDExOTI5LCJleHAiOjE3ODY1NDc5Mjl9.ZKVRd_17cgKj2W0_EwszsLkE4PQmk34K1V5OmJNp5O8",
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/dog2_2.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2RvZzJfMi5qcGVnIiwiaWF0IjoxNzU1MDExOTQ1LCJleHAiOjE3ODY1NDc5NDV9.XdLVfJk9UtVDxUGaUBnefNAsk7btXGqLwurcw7hT29w",
    ],
    "type": "Dogs",
    "weight": 18.2,
    "age": 2,
    "breed": "Beagle",
    "gender": "female",
    "location": "Alexandria, Egypt",
    "description": "Gentle and loves cuddles, good with other pets.",
    "characteristics": ["Gentle", "Calm", "Affectionate"],
    "isVaccinated": false,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:16:00Z",
  },
  {
    "id": 3,
    "name": "Rocky",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/dog3_1.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2RvZzNfMS5qcGVnIiwiaWF0IjoxNzU1MDExOTU5LCJleHAiOjE3ODY1NDc5NTl9._tQ67HuoSbk-X7yGd3u4Y1VKCb_PbbLtklI_crrgvXU",
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/dog3_2.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2RvZzNfMi5qcGVnIiwiaWF0IjoxNzU1MDExOTc1LCJleHAiOjE3ODY1NDc5NzV9.8gUXD1qdpeJI3EGlVAPcKEY51byg26sCah0uQ1YFI_A",
    ],
    "type": "Dogs",
    "weight": 22.0,
    "age": 4,
    "breed": "German Shepherd",
    "gender": "male",
    "location": "Giza, Egypt",
    "description": "Alert and intelligent, great for active owners.",
    "characteristics": ["Loyal", "Protective", "Smart"],
    "isVaccinated": false,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:17:00Z",
  },
  {
    "id": 4,
    "name": "Luna",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/dog4.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2RvZzQuanBlZyIsImlhdCI6MTc1NTAxMTk4OCwiZXhwIjoxNzg2NTQ3OTg4fQ.05dWtfq_089K1Lfq4LZsjkmBhZsWU9y7Y5Gyu5_0iq8",
    ],
    "type": "Dogs",
    "weight": 12.5,
    "age": 1,
    "breed": "Pomeranian",
    "gender": "female",
    "location": "Mansoura, Egypt",
    "description": "Small and fluffy with a cheerful personality.",
    "characteristics": ["Cheerful", "Small", "Friendly"],
    "isVaccinated": true,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:18:00Z",
  },

  // 🐱 Cats
  {
    "id": 5,
    "name": "Simba",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/cat1_1.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2NhdDFfMS5qcGciLCJpYXQiOjE3NTUwMTIwMDcsImV4cCI6MTc4NjU0ODAwN30.3ozXlBNG7xl44wk0LVYPkHT6xZieqfsBeQ4jtpkfEGY",
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/cat1_2.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2NhdDFfMi5qcGVnIiwiaWF0IjoxNzU1MDEyMDIwLCJleHAiOjE3ODY1NDgwMjB9.bHEu_rt1gTVYmnIlRYZ1ORHJ86c5PqA3mdRN5Hu51OU",
    ],
    "type": "Cats",
    "weight": 4.5,
    "age": 2,
    "breed": "Persian",
    "gender": "male",
    "location": "Cairo, Egypt",
    "description": "Calm and affectionate, loves to nap in sunny spots.",
    "characteristics": ["Calm", "Gentle", "Affectionate"],
    "isVaccinated": true,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:19:00Z",
  },
  {
    "id": 6,
    "name": "Nala",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/cat2_1.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2NhdDJfMS5qcGVnIiwiaWF0IjoxNzU1MDEyMDM1LCJleHAiOjE3ODY1NDgwMzV9.iCxWBA8D1H-Diy1Lp5j5XF6PsvFoRBX4s8uh_TtT3B0",
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/cat2_2.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2NhdDJfMi5qcGVnIiwiaWF0IjoxNzU1MDEyMDQ1LCJleHAiOjE3ODY1NDgwNDV9.ODs-hzjr_s2TB-gHVuyCmpC8kJyVxoW-sxChYEl79QI",
    ],
    "type": "Cats",
    "weight": 3.8,
    "age": 1,
    "breed": "Siamese",
    "gender": "female",
    "location": "Alexandria, Egypt",
    "description": "Active and curious, loves to explore.",
    "characteristics": ["Curious", "Active", "Playful"],
    "isVaccinated": false,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:20:00Z",
  },
  {
    "id": 7,
    "name": "Oliver",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/cat3.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2NhdDMuanBlZyIsImlhdCI6MTc1NTAxMjA1OCwiZXhwIjoxNzg2NTQ4MDU4fQ.IT8XmQukB6H2F6mwEmvDkRUW_XEzK22fLjgAQpNWxW8",
    ],
    "type": "Cats",
    "weight": 5.0,
    "age": 4,
    "breed": "Maine Coon",
    "gender": "male",
    "location": "Tanta, Egypt",
    "description": "Large and fluffy, very friendly with kids.",
    "characteristics": ["Friendly", "Fluffy", "Gentle"],
    "isVaccinated": false,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:21:00Z",
  },
  {
    "id": 8,
    "name": "Misty",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/cat4_1.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2NhdDRfMS5qcGVnIiwiaWF0IjoxNzU1MDEyMDY3LCJleHAiOjE3ODY1NDgwNjd9.J9w4KIj_553WBBivipfZqgcSQL3liAEl-KVn-eLQe48",
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/cat4_2.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2NhdDRfMi5qcGVnIiwiaWF0IjoxNzU1MDEyMDgxLCJleHAiOjE3ODY1NDgwODF9.N6N3JHUmo87qXt0FolVLXplfjXrsobPN07_bKoaEckU",
    ],
    "type": "Cats",
    "weight": 3.2,
    "age": 3,
    "breed": "Egyptian Mau",
    "gender": "female",
    "location": "Aswan, Egypt",
    "description": "Sweet and quiet, perfect for a calm home.",
    "characteristics": ["Quiet", "Sweet", "Relaxed"],
    "isVaccinated": true,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:22:00Z",
  },

  // 🐢 Turtles
  {
    "id": 9,
    "name": "Shelly",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/turtle1.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL3R1cnRsZTEuanBnIiwiaWF0IjoxNzU1MDEyMDk3LCJleHAiOjE3ODY1NDgwOTd9.Em1GKZwO1ifEpPj6ayh4Wib-cSh27H1Vsm_d3cd8gzE",
    ],
    "type": "Turtles",
    "weight": 1.2,
    "age": 5,
    "breed": "Red-Eared Slider",
    "gender": "female",
    "location": "Cairo, Egypt",
    "description": "Loves basking under the sun and swimming.",
    "characteristics": ["Calm", "Long-Lived", "Gentle"],
    "isVaccinated": true,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:23:00Z",
  },
  {
    "id": 10,
    "name": "Leo",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/turtle2.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL3R1cnRsZTIuanBlZyIsImlhdCI6MTc1NTAxMjEwNywiZXhwIjoxNzg2NTQ4MTA3fQ.R4zIjjVVSW1I8d2EF6skjn70vOGKo8Gc_vPsDAz59zA",
    ],
    "type": "Turtles",
    "weight": 0.9,
    "age": 3,
    "breed": "Egyptian Turtle",
    "gender": "male",
    "location": "Alexandria, Egypt",
    "description": "Small and easy to care for, enjoys fresh greens.",
    "characteristics": ["Docile", "Small", "Easy Care"],
    "isVaccinated": false,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:24:00Z",
  },

  // 🐦 Birds
  {
    "id": 13,
    "name": "Sky",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/bird1.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2JpcmQxLmpwZWciLCJpYXQiOjE3NTUwMTIxMjIsImV4cCI6MTc4NjU0ODEyMn0.-xjTUvLgWfovcTutBvtJQchBEIOIFaIx1ef3-XdP3Tg",
    ],
    "type": "Birds",
    "weight": 0.2,
    "age": 1,
    "breed": "Budgerigar",
    "gender": "male",
    "location": "Cairo, Egypt",
    "description": "Bright and chirpy, loves human interaction.",
    "characteristics": ["Chirpy", "Friendly", "Colorful"],
    "isVaccinated": true,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:27:00Z",
  },
  {
    "id": 14,
    "name": "Sunny",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/bird2.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2JpcmQyLmpwZWciLCJpYXQiOjE3NTUwMTIxMzAsImV4cCI6MTc4NjU0ODEzMH0.sjGMJzIBCUxQnKQXSbENThKtDoVf2MOk8dYXMeDEYdQ",
    ],
    "type": "Birds",
    "weight": 0.18,
    "age": 2,
    "breed": "Canary",
    "gender": "female",
    "location": "Alexandria, Egypt",
    "description": "Sweet singing voice and low maintenance.",
    "characteristics": ["Singer", "Calm", "Low Maintenance"],
    "isVaccinated": false,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:28:00Z",
  },
  {
    "id": 15,
    "name": "Rio",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/bird3.webp?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2JpcmQzLndlYnAiLCJpYXQiOjE3NTUwMTIxNDIsImV4cCI6MTc4NjU0ODE0Mn0.rZPvwRwl1MFdEVyVMjYtNOQfbAJNef0OSv1KNn7I9Sk",
    ],
    "type": "Birds",
    "weight": 0.25,
    "age": 3,
    "breed": "Cockatiel",
    "gender": "male",
    "location": "Giza, Egypt",
    "description": "Social and intelligent, enjoys mimicking sounds.",
    "characteristics": ["Intelligent", "Social", "Playful"],
    "isVaccinated": false,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:29:00Z",
  },
  {
    "id": 16,
    "name": "Peach",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/bird4.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL2JpcmQ0LmpwZWciLCJpYXQiOjE3NTUwMTIxNTMsImV4cCI6MTc4NjU0ODE1M30.Z0NhNfMd4jClY8zdIHr6LIq3saUxqijFi9g9q2ZAVxs",
    ],
    "type": "Birds",
    "weight": 0.22,
    "age": 1,
    "breed": "Lovebird",
    "gender": "female",
    "location": "Mansoura, Egypt",
    "description": "Affectionate and colorful, loves companionship.",
    "characteristics": ["Affectionate", "Colorful", "Active"],
    "isVaccinated": true,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:30:00Z",
  },

  // 🐇 Rabbits
  {
    "id": 18,
    "name": "Daisy",
    "images": [
      "https://liwxmmxxsuilzxyvoieh.supabase.co/storage/v1/object/sign/pets/rabbit.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV85ZjA2NTNlOC0zZDI1LTRiNjQtYjhlYi0xMmRjNTVkYTYyYmQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJwZXRzL3JhYmJpdC5qcGVnIiwiaWF0IjoxNzU1MDEyMTY1LCJleHAiOjE3ODY1NDgxNjV9.lKgKXjXxpyQpFIgazuRPSddHKJkp6X077jusirDTwyY",
    ],
    "type": "rabbit",
    "weight": 2.0,
    "age": 1,
    "breed": "Mini Rex",
    "gender": "female",
    "location": "Alexandria, Egypt",
    "description": "Curious and loves hopping around the garden.",
    "characteristics": ["Curious", "Playful", "Active"],
    "isVaccinated": false,
    "createdBy": "0000",
    "createdAt": "2025-08-12T10:32:00Z",
  },
];

void uploadData() {
  for (var x in demoPosts) {
    FirebaseFirestore.instance.collection("posts").add(x.toJson());
    print(
      "$x uploaded successfully ======================================================",
    );
  }
}
